spring.datasource.url: jdbc:postgresql://localhost:5432/carRepair
spring.datasource.username: postgres
spring.datasource.password: 12345678
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update

